# Cyb3rhq App Copyright (C) 2017, Cyb3rhq Inc. (License GPLv2)
version: '3.7'

services:
  cyb3rhq.manager:
    build:
      context: cyb3rhq-manager/
      args:
        CYB3RHQ_VERSION: ${CYB3RHQ_VERSION}
        CYB3RHQ_TAG_REVISION: ${CYB3RHQ_TAG_REVISION}
        FILEBEAT_TEMPLATE_BRANCH: ${FILEBEAT_TEMPLATE_BRANCH}
        CYB3RHQ_FILEBEAT_MODULE: ${CYB3RHQ_FILEBEAT_MODULE}
    image: cyb3rhq/cyb3rhq-manager:${CYB3RHQ_IMAGE_VERSION}
    hostname: cyb3rhq.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://cyb3rhq.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - cyb3rhq_api_configuration:/var/ossec/api/configuration
      - cyb3rhq_etc:/var/ossec/etc
      - cyb3rhq_logs:/var/ossec/logs
      - cyb3rhq_queue:/var/ossec/queue
      - cyb3rhq_var_multigroups:/var/ossec/var/multigroups
      - cyb3rhq_integrations:/var/ossec/integrations
      - cyb3rhq_active_response:/var/ossec/active-response/bin
      - cyb3rhq_agentless:/var/ossec/agentless
      - cyb3rhq_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  cyb3rhq.indexer:
    build:
      context: cyb3rhq-indexer/
      args:
        CYB3RHQ_VERSION: ${CYB3RHQ_VERSION}
        CYB3RHQ_TAG_REVISION: ${CYB3RHQ_TAG_REVISION}
    image: cyb3rhq/cyb3rhq-indexer:${CYB3RHQ_IMAGE_VERSION}
    hostname: cyb3rhq.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  cyb3rhq.dashboard:
    build:
      context: cyb3rhq-dashboard/
      args:
        CYB3RHQ_VERSION: ${CYB3RHQ_VERSION}
        CYB3RHQ_TAG_REVISION: ${CYB3RHQ_TAG_REVISION}
        CYB3RHQ_UI_REVISION: ${CYB3RHQ_UI_REVISION}
    image: cyb3rhq/cyb3rhq-dashboard:${CYB3RHQ_IMAGE_VERSION}
    hostname: cyb3rhq.dashboard
    restart: always
    ports:
      - 443:443
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - SERVER_SSL_ENABLED=false
      - CYB3RHQ_API_URL=https://cyb3rhq.manager
    depends_on:
      - cyb3rhq.indexer
    links:
      - cyb3rhq.indexer:cyb3rhq.indexer
      - cyb3rhq.manager:cyb3rhq.manager

volumes:
  cyb3rhq_api_configuration:
  cyb3rhq_etc:
  cyb3rhq_logs:
  cyb3rhq_queue:
  cyb3rhq_var_multigroups:
  cyb3rhq_integrations:
  cyb3rhq_active_response:
  cyb3rhq_agentless:
  cyb3rhq_wodles:
  filebeat_etc:
  filebeat_var:
