file:
  /etc/filebeat/filebeat.yml:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/bin/cyb3rhq-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/lists/audit-keys:
    exists: true
    mode: "0660"
    owner: cyb3rhq
    group: cyb3rhq
    filetype: file
    contains: []
  /var/ossec/etc/ossec.conf:
    exists: true
    mode: "0660"
    owner: root
    group: cyb3rhq
    filetype: file
    contains: []
  /var/ossec/etc/rules/local_rules.xml:
    exists: true
    mode: "0660"
    owner: cyb3rhq
    group: cyb3rhq
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.cert:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.key:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
package:
  filebeat:
    installed: true
    versions:
    - 7.10.2
  cyb3rhq-manager:
    installed: true
    versions:
    - 5.0.0-1
port:
  tcp:1514:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
process:
  filebeat:
    running: true
  cyb3rhq-analysisd:
    running: true
  cyb3rhq-authd:
    running: true
  cyb3rhq-execd:
    running: true
  cyb3rhq-monitord:
    running: true
  cyb3rhq-remoted:
    running: true
  cyb3rhq-syscheckd:
    running: true
  s6-supervise:
    running: true
  cyb3rhq-db:
    running: true
  cyb3rhq-modulesd:
    running: true
user:
  cyb3rhq:
    exists: true
    groups:
    - cyb3rhq
    home: /var/ossec
    shell: /sbin/nologin
group:
  cyb3rhq:
    exists: true