# Cyb3rhq App Copyright (C) 2017, Cyb3rhq Inc. (License GPLv2)
version: '3.7'

services:
  cyb3rhq.manager:
    image: cyb3rhq/cyb3rhq-manager:5.0.0
    hostname: cyb3rhq.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      INDEXER_URL: https://cyb3rhq.indexer:9200
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: admin
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: cyb3rhq-wui
      API_PASSWORD: MyS3cr37P450r.*-
    volumes:
      - cyb3rhq_api_configuration:/var/ossec/api/configuration
      - cyb3rhq_etc:/var/ossec/etc
      - cyb3rhq_logs:/var/ossec/logs
      - cyb3rhq_queue:/var/ossec/queue
      - cyb3rhq_var_multigroups:/var/ossec/var/multigroups
      - cyb3rhq_integrations:/var/ossec/integrations
      - cyb3rhq_active_response:/var/ossec/active-response/bin
      - cyb3rhq_agentless:/var/ossec/agentless
      - cyb3rhq_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/cyb3rhq_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.manager.pem:/etc/ssl/filebeat.pem
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/cyb3rhq_cluster/cyb3rhq_manager.conf:/cyb3rhq-config-mount/etc/ossec.conf

  cyb3rhq.indexer:
    image: cyb3rhq/cyb3rhq-indexer:5.0.0
    hostname: cyb3rhq.indexer
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      bootstrap.memory_lock: "true"
      NODE_NAME: "cyb3rhq.indexer"
      CLUSTER_INITIAL_MASTER_NODES: "cyb3rhq.indexer"
      CLUSTER_NAME: "cyb3rhq-cluster"
      PATH_DATA: /var/lib/cyb3rhq-indexer
      PATH_LOGS: /var/log/cyb3rhq-indexer
      HTTP_PORT: 9200-9299
      TRANSPORT_TCP_PORT: 9300-9399
      COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION: "true"
      PLUGINS_SECURITY_SSL_HTTP_PEMCERT_FILEPATH: /usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.pem
      PLUGINS_SECURITY_SSL_HTTP_PEMKEY_FILEPATH: /usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.key
      PLUGINS_SECURITY_SSL_HTTP_PEMTRUSTEDCAS_FILEPATH: /usr/share/cyb3rhq-indexer/certs/root-ca.pem
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMCERT_FILEPATH: /usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.pem
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMKEY_FILEPATH: /usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.key
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH: /usr/share/cyb3rhq-indexer/certs/root-ca.pem
      PLUGINS_SECURITY_SSL_HTTP_ENABLED: "true"
      PLUGINS_SECURITY_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION: "false"
      PLUGINS_SECURITY_SSL_TRANSPORT_RESOLVE_HOSTNAME: "false"
      PLUGINS_SECURITY_AUTHCZ_ADMIN_DN: "CN=admin,OU=Cyb3rhq,O=Cyb3rhq,L=California,C=US"
      PLUGINS_SECURITY_CHECK_SNAPSHOT_RESTORE_WRITE_PRIVILEGES: "true"
      PLUGINS_SECURITY_ENABLE_SNAPSHOT_RESTORE_PRIVILEGE: "true"
      PLUGINS_SECURITY_NODES_DN: "CN=cyb3rhq.indexer,OU=Cyb3rhq,O=Cyb3rhq,L=California,C=US"
      PLUGINS_SECURITY_RESTAPI_ROLES_ENABLED: '["all_access", "security_rest_api_access"]'
      PLUGINS_SECURITY_SYSTEM_INDICES_ENABLED: "true"
      PLUGINS_SECURITY_SYSTEM_INDICES_INDICES: '[".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]'
      PLUGINS_SECURITY_ALLOW_DEFAULT_INIT_SECURITYINDEX: "true"
      CLUSTER_ROUTING_ALLOCATION_DISK_THRESHOLD_ENABLED: "false"
    volumes:
      - cyb3rhq-indexer-data:/var/lib/cyb3rhq-indexer
      - ./config/cyb3rhq_indexer_ssl_certs/root-ca.pem:/usr/share/cyb3rhq-indexer/certs/root-ca.pem
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.indexer-key.pem:/usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.key
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.indexer.pem:/usr/share/cyb3rhq-indexer/certs/cyb3rhq.indexer.pem
      - ./config/cyb3rhq_indexer_ssl_certs/admin.pem:/usr/share/cyb3rhq-indexer/certs/admin.pem
      - ./config/cyb3rhq_indexer_ssl_certs/admin-key.pem:/usr/share/cyb3rhq-indexer/certs/admin-key.pem
      #  if you need mount a custom opensearch.yml, uncomment the next line and delete the environment variables
      # - ./config/cyb3rhq_indexer/cyb3rhq.indexer.yml:/usr/share/cyb3rhq-indexer/opensearch.yml

  cyb3rhq.dashboard:
    image: cyb3rhq/cyb3rhq-dashboard:5.0.0
    hostname: cyb3rhq.dashboard
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 443:5601
    environment:
      CYB3RHQ_API_URL: https://cyb3rhq.manager
      DASHBOARD_USERNAME: kibanaserver
      DASHBOARD_PASSWORD: kibanaserver
      API_USERNAME: cyb3rhq-wui
      API_PASSWORD: MyS3cr37P450r.*-
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
      OPENSEARCH_HOSTS: https://cyb3rhq.indexer:9200
      OPENSEARCH_SSL_VERIFICATIONMODE: certificate
      OPENSEARCH_REQUESTHEADERSALLOWLIST: '["securitytenant","Authorization"]'
      OPENSEARCH_SECURITY_MULTITENANCY_ENABLED: "false"
      SERVER_SSL_ENABLED: "true"
      OPENSEARCH_SECURITY_READONLY_MODE_ROLES: '["kibana_read_only"]'
      SERVER_SSL_KEY: "/usr/share/cyb3rhq-dashboard/certs/cyb3rhq-dashboard-key.pem"
      SERVER_SSL_CERTIFICATE: "/usr/share/cyb3rhq-dashboard/certs/cyb3rhq-dashboard.pem"
      OPENSEARCH_SSL_CERTIFICATEAUTHORITIES: '["/usr/share/cyb3rhq-dashboard/certs/root-ca.pem"]'
      UISETTINGS_OVERRIDES_DEFAULTROUTE: /app/wz-home
    volumes:
      - cyb3rhq-dashboard-config:/usr/share/cyb3rhq-dashboard/data/cyb3rhq/config
      - cyb3rhq-dashboard-custom:/usr/share/cyb3rhq-dashboard/plugins/cyb3rhq/public/assets/custom
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.dashboard.pem:/usr/share/cyb3rhq-dashboard/certs/cyb3rhq-dashboard.pem
      - ./config/cyb3rhq_indexer_ssl_certs/cyb3rhq.dashboard-key.pem:/usr/share/cyb3rhq-dashboard/certs/cyb3rhq-dashboard-key.pem
      - ./config/cyb3rhq_indexer_ssl_certs/root-ca.pem:/usr/share/cyb3rhq-dashboard/certs/root-ca.pem
      - ./config/cyb3rhq_dashboard/cyb3rhq.yml:/cyb3rhq-config-mount/data/cyb3rhq/config/cyb3rhq.yml
      #  if you need mount a custom opensearch-dashboards.yml, uncomment the next line and delete the environment variables
      # - ./config/cyb3rhq_dashboard/opensearch_dashboards.yml:/cyb3rhq-config-mount/config/opensearch_dashboards.yml
    depends_on:
      - cyb3rhq.indexer
    links:
      - cyb3rhq.indexer:cyb3rhq.indexer
      - cyb3rhq.manager:cyb3rhq.manager

volumes:
  cyb3rhq_api_configuration:
  cyb3rhq_etc:
  cyb3rhq_logs:
  cyb3rhq_queue:
  cyb3rhq_var_multigroups:
  cyb3rhq_integrations:
  cyb3rhq_active_response:
  cyb3rhq_agentless:
  cyb3rhq_wodles:
  filebeat_etc:
  filebeat_var:
  cyb3rhq-indexer-data:
  cyb3rhq-dashboard-config:
  cyb3rhq-dashboard-custom:
