nodes:
  # Cyb3rhq indexer server nodes
  indexer:
    - name: cyb3rhq1.indexer
      ip: cyb3rhq1.indexer
    - name: cyb3rhq2.indexer
      ip: cyb3rhq2.indexer
    - name: cyb3rhq3.indexer
      ip: cyb3rhq3.indexer

  # Cyb3rhq server nodes
  # Use node_type only with more than one Cyb3rhq manager
  server:
    - name: cyb3rhq.master
      ip: cyb3rhq.master
      node_type: master
    - name: cyb3rhq.worker
      ip: cyb3rhq.worker
      node_type: worker

  # Cyb3rhq dashboard node
  dashboard:
    - name: cyb3rhq.dashboard
      ip: cyb3rhq.dashboard
